name: Deploy Pages

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 获取代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v5

      - name: 上传网站文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: 部署网站
        id: deployment
        uses: actions/deploy-pages@v4